In [6]:
import pandas as pd
from datetime import datetime

In [7]:
old_data = pd.read_csv('../Data/Production/matches.csv')
new_data = pd.read_csv('../Data/Staging/feature_table.csv')

In [8]:
old_data.head()

,Unnamed: 0,Player 1,Player 2,Winner,Score,Tournament Name,Year,Player 1 Ranking,Player 2 Ranking,Date,Surface,Player 1 Previous Wins,Player 2 Previous Wins,P1 Surface Wins,P1 Surface Matches,P2 Surface Wins,P2 Surface Matches,P1 Last 10 Matches,P2 Last 10 Matches
0,0,Lleyton Hewitt,Guillermo Canas,Lleyton Hewitt,6364.0,'S-Hertogenbosch,2001,-1.0,-1.0,2001-06-18,Grass,1.0,0.0,10.0,10.0,4.0,5.0,8.0,7.0
1,1,Lleyton Hewitt,Roger Federer,Lleyton Hewitt,6462.0,'S-Hertogenbosch,2001,6.0,15.0,2001-06-18,Grass,0.0,0.0,10.0,10.0,5.0,7.0,8.0,7.0
2,2,Guillermo Canas,Tommy Robredo,Guillermo Canas,7564.0,'S-Hertogenbosch,2001,61.0,69.0,2001-06-18,Grass,1.0,0.0,4.0,5.0,3.0,4.0,7.0,6.0
3,3,Lleyton Hewitt,Gilles Elseneer,Lleyton Hewitt,6264.0,'S-Hertogenbosch,2001,6.0,323.0,2001-06-18,Grass,0.0,0.0,10.0,10.0,4.0,6.0,8.0,4.0
4,4,Roger Federer,Raemon Sluiter,Roger Federer,676464.0,'S-Hertogenbosch,2001,15.0,107.0,2001-06-18,Grass,0.0,0.0,5.0,7.0,4.0,6.0,7.0,3.0

In [15]:
player_1 = 'Lleyton Hewitt'
player_2 = 'Roger Federer'
date = datetime(2011, 6, 18)
new_data[((new_data['Player 1'] == player_1) & (new_data['Player 2'] == player_2)) | ((new_data['Player 2'] == player_1) & (new_data['Player 1'] == player_2))]

,Unnamed: 0,Player 1,Player 2,Tournament Name,Round,Year,Start Date,End Date,Surface,P1 Previous Wins,P2 Previous Wins,P1 Last 10 Matches,P2 Last 10 Matches,P1 Surface Matches,P1 Surface Wins,P2 Surface Matches,P2 Surface Wins,P1 Ranking,P2 Ranking,Winner
1618,1618,Lleyton Hewitt,Roger Federer,'S-Hertogenbosch,Semi-Finals,2001,2001-06-18,2001-06-24,Grass,0,0,10,8,101,64,3,2,6.0,14.0,0
3634,3634,Roger Federer,Lleyton Hewitt,Miami,Semi-Finals,2002,2002-03-18,2002-03-31,Hard,0,1,7,10,60,45,75,63,14.0,1.0,0
5703,5703,Lleyton Hewitt,Roger Federer,Paris,Quarter-Finals,2002,2002-10-28,2002-11-03,Hard,1,1,6,8,105,86,85,63,1.0,8.0,0
5715,5715,Roger Federer,Lleyton Hewitt,Tennis Masters Cup,Semi-Finals,2002,2002-11-11,2002-11-17,Hard,1,2,7,7,88,65,110,90,6.0,1.0,1
8916,8916,Roger Federer,Lleyton Hewitt,Australian Open,Round of 16,2004,2004-01-19,2004-02-01,Hard,1,3,8,9,151,116,155,127,2.0,15.0,0
9885,9885,Roger Federer,Lleyton Hewitt,Hamburg,Semi-Finals,2004,2004-05-10,2004-05-16,Clay,2,3,8,8,50,34,39,27,1.0,19.0,0
10278,10278,Lleyton Hewitt,Roger Federer,Wimbledon,Quarter-Finals,2004,2004-06-21,2004-07-04,Grass,3,3,8,9,24,20,38,31,10.0,1.0,1
11065,11065,Lleyton Hewitt,Roger Federer,Us Open,Finals,2004,2004-08-30,2004-09-12,Hard,3,4,10,8,195,159,183,144,5.0,1.0,1
11661,11661,Lleyton Hewitt,Roger Federer,Tennis Masters Cup,Round Robin,2004,2004-11-15,2004-11-21,Hard,3,6,8,10,209,170,195,156,3.0,1.0,1
11662,11662,Lleyton Hewitt,Roger Federer,Tennis Masters Cup,Finals,2004,2004-11-15,2004-11-21,Hard,3,5,7,10,209,170,195,156,3.0,1.0,1
12341,12341,Roger Federer,Lleyton Hewitt,Indian Wells,Finals,2005,2005-03-07,2005-03-20,Hard,7,3,10,9,221,181,229,186,1.0,2.0,0
13277,13277,Roger Federer,Lleyton Hewitt,Wimbledon,Semi-Finals,2005,2005-06-20,2005-07-03,Grass,8,3,10,9,50,43,29,24,1.0,2.0,0
14076,14076,Lleyton Hewitt,Roger Federer,Us Open,Semi-Finals,2005,2005-08-29,2005-09-11,Hard,3,9,9,10,244,197,239,199,3.0,1.0,1
20940,20940,Roger Federer,Lleyton Hewitt,Montreal,Quarter-Finals,2007,2007-08-05,2007-08-12,Hard,10,3,9,7,331,286,303,238,1.0,21.0,0
20998,20998,Roger Federer,Lleyton Hewitt,Cincinnati,Semi-Finals,2007,2007-08-13,2007-08-19,Hard,11,3,9,7,336,290,307,241,1.0,21.0,0
24609,24609,Lleyton Hewitt,Roger Federer,Wimbledon,Round of 16,2008,2008-06-23,2008-07-06,Grass,3,12,6,9,44,36,81,74,27.0,1.0,1
30026,30026,Roger Federer,Lleyton Hewitt,Cincinnati,Quarter-Finals,2009,2009-08-16,2009-08-23,Hard,13,3,9,7,425,362,365,276,1.0,40.0,0
30174,30174,Lleyton Hewitt,Roger Federer,Us Open,Round of 32,2009,2009-08-31,2009-09-13,Hard,3,14,6,8,369,279,430,367,32.0,1.0,1
31592,31592,Lleyton Hewitt,Roger Federer,Australian Open,Round of 16,2010,2010-01-18,2010-01-31,Hard,3,15,7,7,381,286,451,382,22.0,1.0,1
33489,33489,Lleyton Hewitt,Roger Federer,Halle,Finals,2010,2010-06-07,2010-06-13,Grass,3,16,6,8,53,43,95,87,33.0,1.0,0
53510,53510,Lleyton Hewitt,Roger Federer,Brisbane,Finals,2014,2014-12-29,2014-01-05,Hard,4,16,6,8,469,330,706,597,50.0,2.0,0