In [3]:
import pandas as pd
import os
import sys
from tqdm.auto import tqdm
import json
# Get the current directory.
current_dir = os.getcwd()
# Add the `src` folder to the PYTHONPATH.
sys.path.append(os.path.join(current_dir, "../src"))
from scraping_functions import *

## Collect Tournaments

In [4]:
tournaments = pd.DataFrame({'Name' : [], 'Id' : [], 'Start Date' : [], 'End Date' : []})
for year in tqdm(range(2024, 2000, -1), desc="Collecting tournaments", unit="year"):
    addition = collect_tournaments(year)
    tournaments = pd.concat([tournaments, addition], axis=0)
    break # added for demo purposes

tournaments['Id']=tournaments['Id'].astype('int64')
tournaments['Year'] = tournaments['Start Date'].dt.year
tournaments = tournaments.dropna(subset='Year')
tournaments['Year'] = tournaments['Year'].astype('int64')
tournaments_df = tournaments.drop_duplicates().set_index(['Name', 'Year'])
tournaments_df = tournaments_df.sort_index()
# Filtering out COVID tournaments
covid_start = datetime(2020, 3, 12)
covid_end = datetime(2020, 8, 21)
tournaments_df = tournaments_df[
    ~(
        (tournaments_df['Start Date'] >= covid_start) &
        (tournaments_df['End Date'] <= covid_end)
    )
]
tournaments_df['Number of Rounds'] = tournaments_df['Number of Rounds'].astype('int64')

with open('../Data/Reference/surfaces.json') as file:
    surface_map = json.load(file)
tournaments_df['Surface'] = tournaments_df.index.get_level_values('Name').map(surface_map)
tournaments_df

Collecting tournaments:   0%|          | 0/24 [00:00<?, ?year/s]C:\Users\aman0\AppData\Local\Temp\ipykernel_26916\652784680.py:4: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  tournaments = pd.concat([tournaments, addition], axis=0)
Collecting tournaments:   0%|          | 0/24 [00:18<?, ?year/s]

                         Id Start Date   End Date  Number of Rounds Surface
Name             Year
'S-Hertogenbosch 2024   440 2024-06-10 2024-06-16                 5   Grass
Acapulco         2024   807 2024-02-26 2024-03-02                 5    Hard
Adelaide         2024  8998 2024-01-08 2024-01-13                 5    Hard
Almaty           2024  9410 2024-10-14 2024-10-20                 5    Hard
Antwerp          2024  7485 2024-10-14 2024-10-20                 5    Hard
...                     ...        ...        ...               ...     ...
Us Open          2024   560 2024-08-26 2024-09-08                 7    Hard
Vienna           2024   337 2024-10-21 2024-10-27                 5    Hard
Washington       2024   418 2024-07-29 2024-08-04                 6    Hard
Wimbledon        2024   540 2024-07-01 2024-07-14                 7   Grass
Winston-Salem    2024  6242 2024-08-18 2024-08-24                 6    Hard

[72 rows x 5 columns]

## Collect Players

In [5]:
players_df = None
i=0
all_additions = []
for tournament in tqdm(tournaments_df.index, desc="Processing tournaments"):
    addition = add_players(tournament, tournaments_df)
    if addition is not None:
        all_additions.append(addition)
    break # Added for demo purposes
if all_additions:    
    players_df = pd.concat(all_additions, axis=0)
players_df = players_df.drop_duplicates().reset_index(drop=True).set_index('Name')
players_df

Processing tournaments:   0%|          | 0/72 [00:00<?, ?it/s]

                             Id
Name
Adam Walton                W09E
Adrian Mannarino           ME82
Aleksandar Vukic           V832
Alex de Minaur             DH58
Alexei Popyrin             P09Z
Arthur Cazaux              C0H0
Arthur Fils                F0F1
Botic van de Zandschulp    V812
Cristian Garin             GD64
David Goffin               GB88
Denis Yevseyev             Y171
Gijs Brouwer               BO10
Jakub Mensik               M0NI
Jordan Thompson            TC61
Karen Khachanov            KE29
Luca Nardi                 N0BG
Mackenzie McDonald         MK66
Marc-Andrea Huesler        HH06
Max Purcell                PH71
Milos Raonic               R975
Miomir Kecmanovic          KI95
Nicolas Moreno De Alboran  MW18
Omar Jasika                J553
Otto Virtanen              V0AM
Rinky Hijikata             H0BH
Roberto Bautista Agut      BD06
Robin Haase                H756
Sebastian Korda            K0AH
Stefano Napolitano         N679
Tallon Griekspoor          GJ37
Terence Atmane             A0GC
Tim van Rijthoven          V942
Tommy Paul                 PL56
Tristan Schoolkate         S0N0
Ugo Humbert                HH26
Wesley Koolhof             KC41
Yu Hsiou Hsu               H09F
Zachary Svajda             S0K7
Zizou Bergs                BU13

## Collect Player Rankings

In [ ]:
player_rankings_df = collect_all_rankings(players_df)

Collecting rankings:   0%|          | 0/3380 [00:02<?, ?player/s]

Sample output (first player parsed):
     Player       Date  Rank
Andrew Ilie 1992-11-16   928
Andrew Ilie 1992-11-09   961
Andrew Ilie 1992-11-02   960
Andrew Ilie 1992-10-26   956
Andrew Ilie 1992-10-19   961
Andrew Ilie 1992-10-12   964
Andrew Ilie 1992-10-05   964
Andrew Ilie 1992-09-28   957

## Collect Matches

In [6]:
matches_df = pd.DataFrame({'Player 1' : [], 'Player 2' : [], 'Winner' : [], 'Tournament Name' : []})
i=0
all_additions = []
for index in tqdm(tournaments_df.index, desc="Collecting tournament data"):
    addition = collect_tourney_data(index, tournaments_df)
    if addition is not None:
        all_additions.append(addition)
    break # Added for demo purposes

if all_additions:
    matches_df = pd.concat([matches_df] + all_additions, axis=0)
    
matches_df = matches_df.reset_index().drop('index', axis = 1)
matches_df['Year'] = matches_df['Year'].astype('int64')
matches_df = matches_df.drop_duplicates().reset_index(drop=True)
matches_df

Collecting tournament data:   0%|          | 0/72 [00:00<?, ?it/s]

,Player 1,Player 2,Winner,Tournament Name,Round,Year
0,Alex de Minaur,Sebastian Korda,Alex de Minaur,'S-Hertogenbosch,Finals,2024
1,Alex de Minaur,Ugo Humbert,Alex de Minaur,'S-Hertogenbosch,Semi-Finals,2024
2,Sebastian Korda,Tallon Griekspoor,Sebastian Korda,'S-Hertogenbosch,Semi-Finals,2024
3,Alex de Minaur,Milos Raonic,Alex de Minaur,'S-Hertogenbosch,Quarter-Finals,2024
4,Sebastian Korda,Tommy Paul,Sebastian Korda,'S-Hertogenbosch,Quarter-Finals,2024
5,Ugo Humbert,Gijs Brouwer,Ugo Humbert,'S-Hertogenbosch,Quarter-Finals,2024
6,Tallon Griekspoor,Aleksandar Vukic,Tallon Griekspoor,'S-Hertogenbosch,Quarter-Finals,2024
7,Alex de Minaur,Zizou Bergs,Alex de Minaur,'S-Hertogenbosch,Round of 16,2024
8,Tommy Paul,Alexei Popyrin,Tommy Paul,'S-Hertogenbosch,Round of 16,2024
9,Ugo Humbert,Arthur Fils,Ugo Humbert,'S-Hertogenbosch,Round of 16,2024
10,Aleksandar Vukic,Karen Khachanov,Aleksandar Vukic,'S-Hertogenbosch,Round of 16,2024
11,Gijs Brouwer,Adrian Mannarino,Gijs Brouwer,'S-Hertogenbosch,Round of 16,2024
12,Tallon Griekspoor,Mackenzie McDonald,Tallon Griekspoor,'S-Hertogenbosch,Round of 16,2024
13,Sebastian Korda,Luca Nardi,Sebastian Korda,'S-Hertogenbosch,Round of 16,2024
14,Milos Raonic,Roberto Bautista Agut,Milos Raonic,'S-Hertogenbosch,Round of 16,2024
15,Adrian Mannarino,Stefano Napolitano,Adrian Mannarino,'S-Hertogenbosch,Round of 32,2024
16,Tallon Griekspoor,Miomir Kecmanovic,Tallon Griekspoor,'S-Hertogenbosch,Round of 32,2024
17,Sebastian Korda,Tristan Schoolkate,Sebastian Korda,'S-Hertogenbosch,Round of 32,2024
18,Milos Raonic,Jordan Thompson,Milos Raonic,'S-Hertogenbosch,Round of 32,2024
19,Roberto Bautista Agut,Marc-Andrea Huesler,Roberto Bautista Agut,'S-Hertogenbosch,Round of 32,2024
20,Zizou Bergs,Tim van Rijthoven,Zizou Bergs,'S-Hertogenbosch,Round of 32,2024
21,Gijs Brouwer,Jakub Mensik,Gijs Brouwer,'S-Hertogenbosch,Round of 32,2024
22,Arthur Fils,Arthur Cazaux,Arthur Fils,'S-Hertogenbosch,Round of 32,2024
23,Mackenzie McDonald,Botic van de Zandschulp,Mackenzie McDonald,'S-Hertogenbosch,Round of 32,2024
24,Luca Nardi,David Goffin,Luca Nardi,'S-Hertogenbosch,Round of 32,2024
25,Alexei Popyrin,Rinky Hijikata,Alexei Popyrin,'S-Hertogenbosch,Round of 32,2024
26,Aleksandar Vukic,Max Purcell,Aleksandar Vukic,'S-Hertogenbosch,Round of 32,2024
27,Tristan Schoolkate,Zizou Bergs,Tristan Schoolkate,'S-Hertogenbosch,2nd Round Qualifying,2024
28,Gijs Brouwer,Cristian Garin,Gijs Brouwer,'S-Hertogenbosch,2nd Round Qualifying,2024
29,Stefano Napolitano,Robin Haase,Stefano Napolitano,'S-Hertogenbosch,2nd Round Qualifying,2024
30,Marc-Andrea Huesler,Otto Virtanen,Marc-Andrea Huesler,'S-Hertogenbosch,2nd Round Qualifying,2024
31,Marc-Andrea Huesler,Adam Walton,Marc-Andrea Huesler,'S-Hertogenbosch,1st Round Qualifying,2024
32,Zizou Bergs,Omar Jasika,Zizou Bergs,'S-Hertogenbosch,1st Round Qualifying,2024
33,Cristian Garin,Denis Yevseyev,Cristian Garin,'S-Hertogenbosch,1st Round Qualifying,2024
34,Tristan Schoolkate,Terence Atmane,Tristan Schoolkate,'S-Hertogenbosch,1st Round Qualifying,2024
35,Otto Virtanen,Zachary Svajda,Otto Virtanen,'S-Hertogenbosch,1st Round Qualifying,2024
36,Stefano Napolitano,Yu Hsiou Hsu,Stefano Napolitano,'S-Hertogenbosch,1st Round Qualifying,2024
37,Gijs Brouwer,Nicolas Moreno De Alboran,Gijs Brouwer,'S-Hertogenbosch,1st Round Qualifying,2024
38,Robin Haase,Wesley Koolhof,Robin Haase,'S-Hertogenbosch,1st Round Qualifying,2024

# Saving Results

In [ ]:
tournaments_df.to_csv('../Data/Staging/tournaments.csv')
players_df.to_csv('../Data/Staging/players.csv')
player_rankings_df.to_csv('../Data/Staging/rankings.csv')
matches_df.to_csv('../Data/Staging/matches.csv')